// This file is automatically generated. Do not edit it directly.
// For auth, use: import { supabase } from "@/lib/supabaseClient";
// This file is kept for backward compatibility
export { supabase } from '@/lib/supabaseClient';
export type { Database } from '@/integrations/supabase/types';